import { InlineKeyboard } from "grammy";

export const chooseTypeCardKeyboard = new InlineKeyboard()
  .text("💳 B2B - R$60", "select_card_B2B")
  .text("💳 BUSINESS - R$80", "select_card_BUSINESS")
  .row()
  .text("💳 BLACK - R$150", "select_card_BLACK")
  .text("💳 BUSINESS ENHANCED - R$60", "select_card_BUSINESS_ENHANCED")
  .row()
  .text("💳 CLASSIC - R$60", "select_card_CLASSIC")
  .text("💳 CORPORATE - R$60", "select_card_CORPORATE")
  .row()
  .text("💳 CORPORATE PURCHASING - R$60", "select_card_CORPORATE_PURCHASING")
  .text("💳 CORPORATE T&E - R$80", "select_card_CORPORATE_TE")
  .row()
  .text("💳 ELECTRON - R$60", "select_card_ELECTRON")
  .text("💳 ELO - R$90", "select_card_ELO")
  .row()
  .text("💳 ENHANCED - R$60", "select_card_ENHANCED")
  .text("💳 GOLD - R$90", "select_card_GOLD")
  .row()
  .text("💳 GOV. CORPORATE T&E - R$60", "select_card_GOVERNMENT_CORPORATE_TE")
  .text("💳 INFINITE - R$150", "select_card_INFINITE")
  .row()
  .text("💳 INFINITE BUSINESS - R$115", "select_card_INFINITE_BUSINESS")
  .text("💳 MICRO BUSINESS - R$60", "select_card_MICRO_BUSINESS")
  .row()
  .text("💳 MIXED PRODUCT - R$60", "select_card_MIXED_PRODUCT")
  .text("💳 PLATINUM - R$110", "select_card_PLATINUM")
  .row()
  .text("💳 PREPAID - R$60", "select_card_PREPAID")
  .text("💳 REWARDS - R$60", "select_card_REWARDS")
  .row()
  .text("💳 SIGNATURE - R$110", "select_card_SIGNATURE")
  .text("💳 STANDARD - R$60", "select_card_STANDARD")
  .row()
  .text("💳 TRADITIONAL - R$60", "select_card_TRADITIONAL")
  .text("💳 WORLD ELITE - R$60", "select_card_WORLD_ELITE")
  .row()
  .text("💳 WORLD - R$60", "select_card_WORLD")
  .text("💳 WORLD ELITE BUSINESS - R$60", "select_card_WORLD_ELITE_FOR_BUSINESS")
  .row()
  .text("💵 Recarregar", "chooseRechargeType")
  .row()
  .text("🔙 Voltar", "main");
